### ISSUE TITLE
"ensure access"

### ISSUE THREAD

**Issue by Caroline-A** [SDGforskning/sdg-strings#10]
Do we treat targets with this formulation the same?

List your targets below.

Target 7.1

**Comment by Caroline-A** [comment]
- Target 2.1 - has action terms
- Target 2.3 ("including through equal access to land") - currently no action terms
- Target 3.7, 3.8 - has action terms
- Target 14.b ("provide access... to resources and markets") - currently no action terms, i.e. research about conflicts that arise because of access to fishing waters would be included

**Comment by MartaLor** [comment]
SDG1 has action terms, defined similar to the way it is done in SDG 3: action= ensure/improve ect NEAR access. In e.g. SDG2 this is done differently

**Comment by Caroline-A** [comment]
_1.4 By 2030, **ensure** that all men and women, in particular the poor and the vulnerable, have **equal rights** to economic resources, as well as **access** to basic services, ownership and control over land and other forms of property, inheritance, natural resources, appropriate new technology and financial services, including microfinance_

- Has ensure + access/rights
- Currently, the string combines access with action terms

_2.1 By 2030, end hunger and **ensure access** by all people, in particular the poor and people in vulnerable situations, including infants, to safe, nutritious and sufficient food all year round._

- Contains "ensure access"
- Currently, the string combines access with action terms

_2.3 By 2030, double the agricultural productivity and incomes of small-scale food producers, in particular women, indigenous peoples, family farmers, pastoralists and fishers, including through secure and **equal access to land**, other productive resources and inputs, knowledge, financial services, markets and opportunities for value addition and non-farm employment._

- This is not "ensure access", but has equal access to land as a mechanism to double productivity/incomes. See issue #9 
- Currently, the string combines access with action terms

_2.5 By 2020, maintain the genetic diversity of seeds, cultivated plants and farmed and domesticated animals and their related wild species, including through soundly managed and diversified seed and plant banks at the national, regional and international levels, and **promote access to** and fair and equitable sharing of benefits arising from the utilization of genetic resources and associated traditional knowledge, as internationally agreed._

- Contains "promote access"
- Currently, the string combines access with action terms

_3.7 By 2030, **ensure universal access** to sexual and reproductive health-care services, including for family planning, information and education, and the integration of reproductive health into national strategies and programmes_

- Contains "ensure access"
- Currently, the string combines access with action terms

_3.8 Achieve universal health coverage, including financial risk protection, **access to** quality essential health-care services and access to safe, effective, quality and affordable essential medicines and vaccines for all_

- Contains "achieve" + "access"
- Currently, the string combines access with action terms
- 3.b has not been edited yet, but covers some of the same themes

_4.1 By 2030, ensure that all girls and boys complete free, equitable and quality primary and secondary education leading to relevant and effective learning outcomes_

- Does not contain access specifically, but phrase 3 does NOT combine it with action terms; combined with quality, free etc. instead

_4.2 By 2030, **ensure** that all girls and boys have **access** to quality early childhood development, care and pre‑primary education so that they are ready for primary education_

- Contains "ensure access"
- Currently, the string does NOT combine access with action terms

_4.5 By 2030, eliminate gender disparities in education and **ensure equal access** to all levels of education and vocational training for the vulnerable, including persons with disabilities, indigenous peoples and children in vulnerable situations_

- Contains "ensure access"
- Currently, the string does combine access with action terms

_7.1 By 2030, **ensure universal access** to affordable, reliable and modern energy services_

- Contains "ensure access"
- Currently, the string does combine access with action terms

_11.1 By 2030, **ensure access** for all to adequate, safe and affordable housing and basic services and upgrade slums_

- Contains "ensure access"
- Currently, the string does NOT combine access with action terms

_11.2 By 2030, **provide access** to safe, affordable, accessible and sustainable transport systems for all, improving road safety, notably by expanding public transport, with special attention to the needs of those in vulnerable situations, women, children, persons with disabilities and older persons_

- Contains "provide access"
- Currently, the string does NOT combine access with action terms

_11.7 By 2030, **provide universal access** to safe, inclusive and accessible, green and public spaces, in particular for women and children, older persons and persons with disabilities_

**Comment by Caroline-A** [comment]
We think that all should have action terms to be consistent. We will update the issue as we edit.

**Comment by Caroline-A** [comment]
- [ ] 4.1 - EHS
- [ ] 4.2 - EHS
- [ ] 11.1 - HMB/IG
- [ ] 11.2 - HMB/IG
- [ ] 14.b - CSA
