### ISSUE TITLE
Term change suggestion SDG1.a - [remittance]

### ISSUE THREAD

**Issue by EliSeland** [SDGforskning/sdg-strings#130]
SDG:1

Target & phrase: a

Suggested term/change: consider adding"remittance" to financial terms, perhaps combined with "inflow" or similar 
(from the abstract: 
"we find that financial development and remittance inflows help ameliorate poverty conditions in developing countries. In addition, we find that remittances substitute for financial development in the poverty-alleviating process.")

Reason: article found in Elicit but not in our search that seems relevant: 10.1016/J.JECONBUS.2017.12.001

**Comment by Caroline-A** [comment]
We decided this was not relevant since remittances are about individual transfers of money, while the target is about larger scale (international/commercial) *investment*.
