### ISSUE TITLE
Term change suggestion SDG1.a/1.b/1.2  - [antipoverty]

### ISSUE THREAD

**Issue by EliSeland** [SDGforskning/sdg-strings#131]
SDG: 1

Target & phrase: b

Suggested term/change: add "antipoverty" as search term (in addition to "anti-poverty")

Reason: This article 10.1037/pha0000230 is not found as it is today, but with the alteration. Also quite a few more using "antipoverty"

**Comment by EliSeland** [comment]
Will also find this one from our test set not found today: 10.1080/00220388.2015.1010157

**Comment by Caroline-A** [comment]
Also 1.2?
