### ISSUE TITLE
Term change suggestion SDG1.2 - [poor families]

### ISSUE THREAD

**Issue by Caroline-A** [SDGforskning/sdg-strings#17]
SDG: 1

Target & phrase: target 1.2

Suggested term/change: Add "families"/"family" to children, communities etc. Consider "low-income" together with "poor"?

Reason: Also likely to be used in the relevant context

**Comment by EliSeland** [comment]
SDG: 7
Target & phrase: 7.1, phrase 3

Suggested term/change: Add "paraf$in" to "dirty fuels"

Reason: Also likely to be used in the relevant context
