### ISSUE TITLE
Interpretation suggestion SDG3 - Target 3.3

### ISSUE THREAD

**Issue by EliSeland** [SDGforskning/sdg-strings#33]
SDG:3
Target: 3 

Suggestion: In topic approach: Consider adding something to the documentation of phrase 2, to say why the action terms are included

Reason:
Nothing is said about it, and it was a difficult decision, may need some more thinking

**Comment by Caroline-A** [comment]
Additional issue after testing - 

How shall we deal with covid research? If the interpretation of the topic approach is "research about pandemics" then we get a lot of papers about e.g. after effects of covid pandemic on social factors etc. Should it be limited the same as the action approach, back to "preventing/limiting epidemics"?

**Comment by Caroline-A** [comment]
Could also consider a whole separate phrase for covid, as it is so dominant. Current version (v.1.2.2):
- Phrase 2 action/topic approach - covid research = 45000/102000 results. 44%
- Phrase 3 action approach - covid research = 86000/173000 results. 50%
- Phrase 3 topic approach - covid research = 370000/640000 results. 58%

NB Consider adding Sars-cov-2 as a synonym for covid
