### ISSUE TITLE
Standardisation of strings for disasters

### ISSUE THREAD

**Issue by Caroline-A** [SDGforskning/sdg-strings#6]
We should check these at the end, it concerns several SDGs:

- 1.5 - By 2030, build the resilience of the poor and those in vulnerable situations and reduce their exposure and vulnerability to **climate-related extreme events and other economic, social and environmental shocks and disasters**
- 2.4 - By 2030, ensure sustainable food production systems and implement **resilient** agricultural practices that increase productivity and production, that help maintain ecosystems, that strengthen capacity for adaptation to **climate change, extreme weather, drought, flooding and other disasters** and that progressively improve land and soil quality.
- 11.5 - By 2030, significantly reduce the number of deaths and the number of people affected and substantially decrease the direct economic losses relative to global gross domestic product caused by **disasters, including water-related disasters**, with a focus on protecting the poor and people in vulnerable situations
- 13.1 - Strengthen resilience and adaptive capacity to **climate-related hazards and natural disasters** in all countries

Suggestion: We check the different strings, and make sure they are standardised as much as possible, but adapted when necessary (in light of the the target language or that a specific term doesn't work in that context, e.g. cytokine storm).

**Comment by Caroline-A** [comment]
We should check what we have against resources to do with Sendai and UNDRR

- https://www.preventionweb.net/sendai-framework/sendai-framework-at-a-glance
- https://www.undrr.org/terminology
- https://www.preventionweb.net/publication/hazard-definition-and-classification-review - appendix 6 has a list of disasters

**Comment by MartaLor** [comment]
SDG01: climate-related extreme events and other economic, social and environmental shocks and disasters
SDG02: climate change, extreme weather, drought, flooding and other disasters
SDG11: disasters, including water-related disasters
SDG13: climate-related hazards and natural disasters

I suggest to assume per default that disasters are defined as the outcomes of “natural”/climate made hazards.  this is what SENDAI mostly is concerned about.
In SDG1 include other economic, social  shocks and disasters. 
In SDG2 include climate change itself, not only  hazards and disasters


      OR ("extreme$" NEAR/3 ("climat*" OR "weather" OR "precipitation" OR "rain" OR "snow" OR "temperature$" OR "storm$"))
      OR "drought$" OR "flood*" OR "cold spells"
      OR "tropical cyclone$" OR "typhoon$" OR "hurricane$" OR "tornado"
      OR "heatwave$" OR "heat-wave$" OR "wildfire*" OR "forest fire*" OR "wild-fire*" OR "forestfire*"
      OR "earthquake$" OR "volcanic activit*" OR "volcanic emission$" OR "volcanic eruption$"
      OR "landslide$" OR "rockslide$" OR "surface collapse$" OR "mud flow$"
      OR "land-slide$" OR "rock-slide$" OR "mud-flow$"
      OR "avalanch*"
      OR ("sea level" NEAR/3 ("chang*" OR "rising" OR "rise$"))

OR

((("natural" OR "anthropogenic" OR "environmental" OR "climat$")
 NEAR/3 ("hazard*" OR "catastroph*" OR "disaster*"))

OR
only SDG2
 ("climate change" OR "climatic change$" OR "global warming" OR "changing climate")
only SDG1 or similar

                      OR (("volatil*" OR "unstable" OR "instability") NEAR/5 ("market$" OR "price$"))
                      OR "financial crash*" OR "economic downturn$"
                      OR "war" OR "wars"
                      OR (("volatil*" OR "unstable" OR "instability" OR "unrest") NEAR/5 ("political$" OR "civil"))
                      OR "outbreak$" OR "disease risk$" OR "pandemic$" OR "epidemic$"
                      )

**Comment by Caroline-A** [comment]
Resolution:

- The string for SDG1 and SDG2 can be alike (natural/climate/economic etc.)
- the string for SDG 11 and 13 can be alike (only natural/climate). 

Caroline will go through the links above and see if the string can have other terms add/more objective choices of terms. Selected terms are already taken from Sendai (subjective choices).

**Comment by Caroline-A** [comment]
Used Murray, V. et al. (2021) Hazard Information Profiles: Supplement to UNDRR-ISC Hazard Definition & Classification Review: Technical Report: Geneva, Switzerland, United Nations Office for Disaster Risk Reduction; Paris, France, International Science Council. DOI: 10.24948/2021.05 ([link](https://www.preventionweb.net/media/73913/download)).

Hazard =/= disaster. A number of hazards on this list do not seem to fit the description of a disaster; for example, "chlorine" is listed as a chemical hazard, but if research is about a chlorine-related disaster it would have to be used together with words such as hazard, catastrophe etc. Therefore some hazards from the list are included where we think they could cause "serious disruption of a community" even when used as a stand-alone term (e.g. tornado); others are included more generically with "disaster" terms (e.g. pesticides).

I have excluded biological disasters from "natural" disasters. 

#### Natural disasters and climate-related hazards
General terms (extreme climate, and natural disasters), then Hydro-meteorological, then Geohazards (not already covered), then Environmental (subset that is related to climate). 

      "extreme$" NEAR/3 ("climat*" OR "weather" OR "precipitation" OR "rain" OR "snow" OR "temperature$" OR "storm$" OR "wind$"))
      OR (("natural" OR "climat*") NEAR/3 ("hazard$" OR "catastrophe$" OR "disaster$"))
      OR "rogue wave$" OR "tsunami$" OR "tropical cyclone$" OR "typhoon$" OR "hurricane$" OR "tornado"
      OR "drought$" OR "flood*" 
      OR "avalanche$" OR "landslide$" OR "land-slide$" OR "rockslide$" OR "rock-slide$" OR "rockfall$" OR "surface collapse$" OR "mudflow$" OR "mud-flow$"
      OR "cold spells" OR "cold wave$" OR "dzud$" OR "blizzard$" OR "heatwave$" OR "heat-wave$"
      OR "earthquake$" OR "volcanic activity" OR "volcanic emission$" OR "volcanic eruption$" OR "ash fall" OR "tephra fall"
      OR "wildfire*" OR "wild-fire*" OR "forest fire*" OR "forestfire*"
      OR ("sea level" NEAR/3 ("chang*" OR "rising" OR "rise$")) 

#### Non-natural disasters and biological disasters
Disasters generally, plus environmental, chemical, biological, technological, and societal disasters. Economic is combined in phrases to prevent e.g. economic costs of disasters. Here we are considering war a disaster, it is on the list of hazards. 

```
"disaster$" OR "catastrophe$"
OR (  ("anthropogenic" 
         OR "environmental" OR "deforestation" OR "desertification" OR "degredation" OR "pollution" OR "erosion"
         OR "chemical" OR "heavy metal$" OR "pesticide$"
         OR "biological" OR "disease" OR "zoonotic"
         OR "technological" OR "radioactive" OR "nuclear" OR "cyber" OR "industrial" OR "construction" OR "transportation"
         ) 
         NEAR/3 ("hazard$" OR "catastrophe$" OR "disaster$")
      ) 
OR "outbreak$" OR "pandemic$" OR "epidemic$"
OR "war" OR "wars" OR "armed conflict$"
OR (("volatil*" OR "unstable" OR "instability" OR "unrest") NEAR/5 ("political$" OR "civil"))
OR "financial crash*" OR "financial shock$" OR "financial disaster$" 
OR "economic downturn$" OR "economic shock$" OR "economic disaster$"

#UNSURE if should count:
OR (("volatil*" OR "unstable" OR "instability") NEAR/5 ("market$" OR "price$"))
```

#### Climate change (only SDG2)

     OR ("climate change" OR "climatic change$" OR "global warming" OR "changing climate")

**Comment by Caroline-A** [comment]
- [ ] 1.5 - CSA now updated https://github.com/SDGforskning/SDGstrings_wos/blob/main/SDG01_query_action_WoS.md#target-15 
- [ ] 2.4 - CSA
- [ ] 11.5 - HMB/IG
- [ ] 13.1 - CSA
