### ISSUE TITLE
Results feedback SDG 3.6 [roadkill]

### ISSUE THREAD

**Issue by Caroline-A** [SDGforskning/sdg-strings#74]
SDG: 3
Target: 3.6
Action or Topic?: Both

Feedback: Several erroneous results about wildlife being killed by traffic. Should be reduced. 

Example result:
http://dx.doi.org/10.1080/23766808.2023.2166270
http://dx.doi.org/10.21608/EJVS.2023.182163.1418
http://dx.doi.org/10.1016/j.scitotenv.2023.163173
http://dx.doi.org/10.1007/s10344-023-01669-z

**Comment by Caroline-A** [comment]
Difficult as many works talking about wildlife are also relevant for research about deaths and injuries from road accidents (due to wildlife-vehicle collisions also being dangerous for humans). 

- Alternative 1: We consider all results about deaths and injuries relevant, even if they are animal injuries, on the basis that these can impact human safety. Counterpoint is that a number of results do not consider humans at all (e.g. talking about wildlife conservation, habitat connectivity etc).
- Alternative 2: A NOT list with terms that capture these conservation works, without losing too many of those about wildlife and human safety. For example, `NOT ("air traffic" OR "boat traffic" OR "roadkill" OR "conservation" OR "biodiversity" OR "at risk species" OR "threatened species" OR "extinct*" OR "habitat connectivity" OR "wildlife rescue" OR "veterinar*")` removes ca. 700 the last 5 years (4%)

**Comment by EliSeland** [comment]
We decided, after a long discussion to do a modified version of alternative 3, ie force the use of "accidents", but without expanding the NOT terms, as that led to the exclusion of too many relevant hits
