### ISSUE TITLE
Results feedback SDG12.4 [CO2 emissions]

### ISSUE THREAD

**Issue by LeenaByh** [SDGforskning/sdg-strings#89]
SDG:12
Target:12.4
Action or Topic: ...environmentally sound management of chemicals and wastes...reduce their release to air, water and soil 

Feedback: CO2 is not mentioned in phrase 3, which searches for specified emissions. I'm not sure if it should be or not. Adding it may bend the phrase quite a bit towards climate change. Should CO2 be added?.  

Example result: https://doi.org/10.1016/j.jenvman.2021.114055

**Comment by Caroline-A** [comment]
The target interpretation is currently "This target is interpreted to cover research about a) sustainable/environmentally sound management of chemicals thoughout their life cycle, and research about international agreements on chemical management. The target also covers b) research about sustainable management of all wastes and c) reducing their release to air, water and soil, as well as research about international agreements on management of hazardous wastes."

Focus is on wastes and chemicals. The topic page from the UN on waste and chemicals has no section on CO2 (https://sdgs.un.org/topics/chemicals-and-waste). I think most would describe this as something else (not a waste or chemical in the sense of the target). So adding reduce + CO2 + emissions goes very far outside our interpretation.
