### ISSUE TITLE
Results feedback SDG12.8 [education & public]

### ISSUE THREAD

**Issue by LeenaByh** [SDGforskning/sdg-strings#91]
SDG:12
Target:12.8
Action or Topic?:...that people everywhere have the relevant information and awareness for sustainable development... 

Feedback: Phrase 1: "Education" had to be linked with "consumers" or "citizens" to exclude noise. Without "education of the public" or "education AND sustainable development" some papers are missed. 

Example result:https://doi.org/10.1016/J.RENENE.2019.03.010

**Comment by Caroline-A** [comment]
Phrase 2: Does this result in noisy health papers? e.g. action/intention/behaviour + consumption (FOOD) + environmental (factors)? e.g. 10.1080/21642850.2023.2208213

**Comment by Caroline-A** [comment]
Phrase 2: Consider checking the effect of "child" vs. "children"? Some noise from e.g. action for sustainable child care 10.1080/16549716.2023.2173853

**Comment by Caroline-A** [comment]
Phrase 1: Add "education for sustainability" as a phrase
