### ISSUE TITLE
Results feedback SDG12.b [very poor recall, should be re-structured?]

### ISSUE THREAD

**Issue by LeenaByh** [SDGforskning/sdg-strings#93]
SDG:12.b
Target:
Action or Topic?:Develop and implement tools to monitor sustainable development impacts for sustainable tourism that creates jobs and promotes local culture and products

Feedback: None of the Elicit references were found by the phrase for 12.b, although all of them were found by the query for the whole 12. The result for 12.b is very slim (539 papers) and our interpretation quite strict (research about monitoring of the economic, social and environmental impacts of sustainable tourism).

Example result:
https://doi.org/10.1080/09669582.2021.1937190
https://doi.org/10.1080/09640568.2021.1978407
https://doi.org/10.1016/J.JHTM.2021.02.006
https://doi.org/10.3390/SU13105701
https://doi.org/10.1002/bse.2420

**Comment by Caroline-A** [comment]
In the python title search, I found better results by dropping the element:
`("impact$" OR "effect$"
              OR (("local" OR "indigenous") NEAR/3 ("community" OR "communities" OR "culture$" OR "people$")) 
              OR "waste" OR "litter" OR "effluent$" OR "pollution" OR "pollute$"
              OR "job$" OR "employment" OR "enterprice$" OR "livelihood$" OR "income$" OR "profit*" 
              OR "econom*" OR "GDP" OR "wealth" OR "poverty" 
              OR "trade" OR "trading" OR "market$" 
              OR "environment*" OR "ecosystem$" OR "biodiversity" OR "wildlife" OR "flora" OR "fauna" OR "nature" 
              )`

So it is just *monitoring + sustainable + tourism* - I think this could help in WOS too.
